apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: webapplication
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
      - name: webapp
        image: bharath0812/test:13.0
        ports:
        - containerPort: 8000
